import React, { useEffect, useRef } from 'react';
import { Info } from 'lucide-react';
import styles from '../ProjectDetails/ProjectDetails.module.css';
import svgPaths from '../../../imports/svg-m590sprq1z';

interface ETRFDataDetailsProps {
  formData: any;
  handleChange: (field: string, value: any) => void;
}

const DateIcon: React.FC = () => (
  <svg width="18" height="18" viewBox="0 0 18 18" fill="none" className={styles.dateIcon}>
    <path d={svgPaths.p24a05d00} fill="#4A4A4A" />
  </svg>
);

export default function ETRFDataDetails({ formData, handleChange }: ETRFDataDetailsProps) {
  const startDateRef = useRef<HTMLInputElement | null>(null);
  const endDateRef = useRef<HTMLInputElement | null>(null);

  useEffect(() => {
    if (!formData.etrfId) {
      const randomSuffix = Math.random().toString(36).substring(2, 9).toUpperCase();
      handleChange('etrfId', `ETRF-${randomSuffix}`);
    }
  }, [formData.etrfId]);

  const isEndDateBeforeStart = (start?: string, end?: string) => {
    if (!start || !end) return false;
    return end < start;
  };

  const openPicker = (ref: React.RefObject<HTMLInputElement | null>) => {
    if (!ref) return;
    const el = ref.current;
    if (!el) return;
    // @ts-ignore
    if (typeof el.showPicker === 'function') {
      // @ts-ignore
      el.showPicker();
    } else {
      el.focus();
      el.click();
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h2 className={styles.title}>ETRF Details</h2>
        <p className={styles.description}>Define project scope, timeline, and requirements</p>
      </div>

      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={styles.label}>Ironclad ID</label>
          <input
            type="text"
            className={styles.input}
            value={formData.ironcladId || ''}
            onChange={(e) => handleChange('ironcladId', e.target.value)}
            placeholder="IC - 45821"
          />
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>Client Name</label>
          <input
            type="text"
            className={styles.input}
            value={formData.clientName || ''}
            onChange={(e) => handleChange('clientName', e.target.value)}
            placeholder="TechCrop Industries"
          />
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>Type of Work</label>
          <select
            className={styles.select}
            value={formData.typeOfWork || ''}
            onChange={(e) => handleChange('typeOfWork', e.target.value)}
          >
            <option value="" hidden></option>
            <option value="Performance Improvement">Performance Improvement</option>
            <option value="Transformational">Transformational</option>
            <option value="Turnaround">Turnaround</option>
          </select>
        </div>
      </div>

      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={styles.label}>Radius ID</label>
          <select
            className={styles.select}
            value={formData.radiusId || ''}
            onChange={(e) => handleChange('radiusId', e.target.value)}
          >
            <option value="" hidden></option>
            <option value="radius-1">Radius 1</option>
            <option value="radius-2">Radius 2</option>
            <option value="radius-3">Radius 3</option>
          </select>
          <p className={styles.additionalInfo}>Recommended: You can skip if not available at the moment.</p>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>SAP Project ID</label>
          <input
            type="text"
            className={styles.input}
            value={formData.sapProjectId || ''}
            onChange={(e) => handleChange('sapProjectId', e.target.value)}
            placeholder="Enter SAP Project ID"
          />
          <p className={styles.additionalInfo}>Recommended: You can skip if not available at the moment.</p>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>ETRF ID</label>
          <input type="text" className={styles.input} value={formData.etrfId || ''} disabled />
          <p className={styles.additionalInfoGray}>Auto Generated by ServiceNow</p>
        </div>
      </div>

      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={styles.label}>
            Project Code Name <span className={styles.required}>*</span>
          </label>
          <input
            type="text"
            className={styles.input}
            value={formData.projectCodeName || ''}
            onChange={(e) => handleChange('projectCodeName', e.target.value)}
            placeholder="Select a name from the list, or add a new one."
          />
          <p className={styles.additionalInfo}>Select a name from the list, or add a new one.</p>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>Expected Start Date</label>
          <input
            ref={startDateRef}
            type="date"
            value={formData.estimatedStartDate || ''}
            onChange={(e) => {
              const nextStart = e.target.value;
              handleChange('estimatedStartDate', nextStart);
              if (isEndDateBeforeStart(nextStart, formData.estimatedEndDate)) {
                alert('Expected End Date should be on or after Expected Start Date.');
                handleChange('estimatedEndDate', '');
              }
            }}
            style={{
              position: 'absolute',
              width: '1px',
              height: '1px',
              padding: 0,
              margin: '-1px',
              overflow: 'hidden',
              clip: 'rect(0 0 0 0)',
              whiteSpace: 'nowrap',
              border: 0,
            }}
            aria-hidden={false}
          />
          <div
            className={styles.dateInput}
            onClick={() => openPicker(startDateRef)}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                openPicker(startDateRef);
              }
            }}
          >
            <DateIcon />
            <input
              type="text"
              readOnly
              value={formData.estimatedStartDate || ''}
              placeholder=""
              className={styles.input}
              style={{
                border: 'none',
                padding: 0,
                margin: 0,
                background: 'transparent',
                color: '#282926',
                cursor: 'pointer',
              }}
              aria-label="Expected start date"
            />
          </div>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>Expected End Date</label>
          <input
            ref={endDateRef}
            type="date"
            value={formData.estimatedEndDate || ''}
            min={formData.estimatedStartDate || undefined}
            onChange={(e) => {
              const nextEnd = e.target.value;
              if (isEndDateBeforeStart(formData.estimatedStartDate, nextEnd)) {
                alert('Expected End Date should be on or after Expected Start Date.');
                return;
              }
              handleChange('estimatedEndDate', nextEnd);
            }}
            style={{
              position: 'absolute',
              width: '1px',
              height: '1px',
              padding: 0,
              margin: '-1px',
              overflow: 'hidden',
              clip: 'rect(0 0 0 0)',
              whiteSpace: 'nowrap',
              border: 0,
            }}
            aria-hidden={false}
          />
          <div
            className={styles.dateInput}
            onClick={() => openPicker(endDateRef)}
            role="button"
            tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                openPicker(endDateRef);
              }
            }}
          >
            <DateIcon />
            <input
              type="text"
              readOnly
              value={formData.estimatedEndDate || ''}
              placeholder=""
              className={styles.input}
              style={{
                border: 'none',
                padding: 0,
                margin: 0,
                background: 'transparent',
                color: '#282926',
                cursor: 'pointer',
              }}
              aria-label="Expected end date"
            />
          </div>
        </div>
      </div>

      <div className={styles.formGroup}>
        <label className={styles.label}>Project Description</label>
        <div className={styles.textareaWrapper}>
          <textarea
            className={styles.textarea}
            value={formData.description || ''}
            onChange={(e) => handleChange('description', e.target.value)}
            maxLength={80}
          />
          <div className={styles.wordCounter}>{(formData.description || '').length}/80</div>
        </div>
      </div>

      <div className={styles.sectionHeader}>
        <h2 className={styles.title}>Data Details</h2>
        <p className={styles.description}>Please provide the necessary data details.</p>
      </div>

      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={styles.label}>
            What data volume do you expect (in GB)? <span className={styles.required}>*</span>
          </label>
          <select
            className={styles.select}
            value={formData.dataVolume || ''}
            onChange={(e) => handleChange('dataVolume', e.target.value)}
          >
            <option value="" hidden></option>
            <option value="<1">Less than 1 GB</option>
            <option value="1-10">1 - 10 GB</option>
            <option value="10-100">10 - 100 GB</option>
            <option value="100-500">100 - 500 GB</option>
            <option value="500+">500+ GB</option>
          </select>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>
            Country of Origin of the Data? <span className={styles.required}>*</span>
          </label>
          <select
            className={styles.select}
            value={formData.dataCountryOrigin || ''}
            onChange={(e) => handleChange('dataCountryOrigin', e.target.value)}
          >
            <option value="" hidden></option>
            <option value="USA">United States</option>
            <option value="UK">United Kingdom</option>
            <option value="India">India</option>
            <option value="Other">Other</option>
          </select>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>
            Does the client permit data transfer abroad? <span className={styles.required}>*</span>
          </label>
          <select
            className={styles.select}
            value={formData.dataTransferAbroad || ''}
            onChange={(e) => handleChange('dataTransferAbroad', e.target.value)}
          >
            <option value="" hidden></option>
            <option value="yes">Yes</option>
            <option value="no">No</option>
          </select>
        </div>
      </div>

      <div className={styles.formGroup}>
        <label className={styles.label}>Privacy/Security Requirements</label>
        <div className={styles.checkboxGrid}>
          {[
            { key: 'tar', label: 'TAR' },
            { key: 'soc2', label: 'SOC 2' },
            { key: 'gdpr', label: 'GDPR' },
            { key: 'sox', label: 'SOX' },
            { key: 'iso27001', label: 'ISO27001' },
            { key: 'ear', label: 'EAR' },
            { key: 'ccpa2018', label: 'CCPA 2018' },
            { key: 'other', label: 'Other/Client Specific' },
          ].map((item) => (
            <label key={item.key} className={styles.checkboxLabel}>
              <input
                type="checkbox"
                checked={formData.privacyRequirements?.[item.key] || false}
                onChange={(e) =>
                  handleChange('privacyRequirements', {
                    ...(formData.privacyRequirements || {}),
                    [item.key]: e.target.checked,
                  })
                }
                className={styles.checkboxInput}
              />
              {item.label}
              <Info size={16} className="text-[#4a4a4a] shrink-0" />
            </label>
          ))}
        </div>
      </div>

      <div className={styles.formGroup} style={{ marginTop: '32px' }}>
        <label className={styles.label}>Data Types Being Collected</label>
        <div className={styles.checkboxGrid}>
          {[
            { key: 'personalData', label: 'Personal data' },
            { key: 'npi', label: 'Non-public information (NPI)' },
            { key: 'pci', label: 'Payment card industry data (PCI-DSS)' },
            { key: 'phi', label: 'Personal health information (PHI)' },
            { key: 'sensitiveData', label: 'Client sensitive/intellectual property data' },
          ].map((item) => (
            <label key={item.key} className={styles.checkboxLabel}>
              <input
                type="checkbox"
                checked={formData.dataTypes?.[item.key] || false}
                onChange={(e) =>
                  handleChange('dataTypes', {
                    ...(formData.dataTypes || {}),
                    [item.key]: e.target.checked,
                  })
                }
                className={styles.checkboxInput}
              />
              {item.label}
              <Info size={16} className="text-[#4a4a4a] shrink-0" />
            </label>
          ))}
        </div>
      </div>
    </div>
  );
}
