import React, { useState } from 'react';
import styles from './ProjectDetails.module.css';
import svgPaths from '../../../imports/svg-m590sprq1z';

const AlertIcon: React.FC = () => (
  <svg width="20" height="20" viewBox="0 0 20 20" fill="none">
    <path d={svgPaths.p341e8200} fill="#CE7309" />
  </svg>
);

const DateIcon: React.FC = () => (
  <svg width="18" height="18" viewBox="0 0 18 18" fill="none">
    <path d={svgPaths.p24a05d00} fill="#4A4A4A" />
  </svg>
);

export const ProjectDetails: React.FC = () => {
  const [formData, setFormData] = useState({
    ertmProjectId: 'PRJ-8YV03FK',
    sapProjectId: '',
    projectCodeName: '',
    projectType: '',
    estimatedStartDate: '',
    estimatedEndDate: '',
    dataType: '',
    description: '',
  });

  const [charCount, setCharCount] = useState(0);

  const handleTextareaChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const text = e.target.value;
    setCharCount(text.length);
    setFormData({ ...formData, description: text });
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h2 className={styles.title}>Project Details</h2>
        <p className={styles.description}>Define project scope, timeline, and requirements</p>
        
        <div className={styles.banner}>
          <AlertIcon />
          <p className={styles.bannerText}>You are creating a new project. Enter project details.</p>
        </div>
      </div>

      {/* Row 1: ERTM Project ID, SAP Project ID, Project Code Name */}
      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={`${styles.label} ${styles.labelGray}`}>
            ERTM Project ID <span className={styles.required}>*</span>
          </label>
          <input
            type="text"
            className={styles.input}
            value={formData.ertmProjectId}
            disabled
          />
          <p className={`${styles.additionalInfo} ${styles.additionalInfoGray}`}>
            Auto Generated by ServiceNow
          </p>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>SAP Project ID</label>
          <select
            className={styles.select}
            value={formData.sapProjectId}
            onChange={(e) => setFormData({ ...formData, sapProjectId: e.target.value })}
          >
            <option value="">Select SAP project ID</option>
            <option value="sap1">SAP-001</option>
            <option value="sap2">SAP-002</option>
          </select>
          <p className={styles.additionalInfo}>Update ASAP if SAP project ID is unavailable.</p>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>
            Project Code Name <span className={styles.required}>*</span>
          </label>
          <select
            className={styles.select}
            value={formData.projectCodeName}
            onChange={(e) => setFormData({ ...formData, projectCodeName: e.target.value })}
          >
            <option value="">Select project code name</option>
            <option value="alpha">Project Alpha</option>
            <option value="beta">Project Beta</option>
          </select>
          <p className={styles.additionalInfo}>Select dynamically generated words.</p>
        </div>
      </div>

      {/* Row 2: Project Type, Start Date, End Date */}
      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={styles.label}>What Type of Project it is?</label>
          <select
            className={styles.select}
            value={formData.projectType}
            onChange={(e) => setFormData({ ...formData, projectType: e.target.value })}
          >
            <option value="">Select type of project</option>
            <option value="internal">Internal</option>
            <option value="external">External</option>
          </select>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>Estimated Start Date</label>
          <div style={{ position: 'relative' }}>
            <input
              type="date"
              className={styles.input}
              value={formData.estimatedStartDate}
              onChange={(e) => setFormData({ ...formData, estimatedStartDate: e.target.value })}
              placeholder="Pick a date"
            />
          </div>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>Estimated End Date</label>
          <div style={{ position: 'relative' }}>
            <input
              type="date"
              className={styles.input}
              value={formData.estimatedEndDate}
              onChange={(e) => setFormData({ ...formData, estimatedEndDate: e.target.value })}
              placeholder="Pick a date"
            />
          </div>
        </div>
      </div>

      {/* Row 3: Data Type */}
      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={styles.label}>Will you use Personal or Protected data?</label>
          <select
            className={styles.select}
            value={formData.dataType}
            onChange={(e) => setFormData({ ...formData, dataType: e.target.value })}
          >
            <option value="">Select option</option>
            <option value="personal">Personal</option>
            <option value="protected">Protected</option>
            <option value="none">None</option>
          </select>
        </div>
      </div>

      {/* Textarea */}
      <div className={styles.formGroup}>
        <label className={styles.label}>Describe your project and its goals.</label>
        <div className={styles.textareaWrapper}>
          <textarea
            className={styles.textarea}
            placeholder="Describe your project objectives and scope"
            value={formData.description}
            onChange={handleTextareaChange}
            maxLength={80}
          />
          <div className={styles.wordCounter}>{charCount}/80</div>
        </div>
      </div>
    </div>
  );
};
