import React, { useRef, useState } from 'react';
import styles from './ProjectDetails.module.css';
import svgPaths from '../../../imports/svg-m590sprq1z';
import { formatDate } from '../Utils/UiUtilis';

interface ProjectDetailsProps {
  data?: any;
  formData: any;
  handleChange: (field: string, value: any) => void;
}


const DateIcon: React.FC = () => (
  <svg width="18" height="18" viewBox="0 0 18 18" fill="none" className={styles.dateIcon}>
    <path d={svgPaths.p24a05d00} fill="#4A4A4A" />
  </svg>
);

export const ProjectDetails: React.FC<ProjectDetailsProps> = ({ data, formData, handleChange }) => {
  const [charCount, setCharCount] = useState(0);

  const startDateRef = useRef<HTMLInputElement | null>(null);
  const endDateRef = useRef<HTMLInputElement | null>(null);



  const formattedStart = formatDate(formData?.estimatedStartDate);
  const formattedEnd = formatDate(formData?.estimatedEndDate);

  const openPicker = (ref: React.RefObject<HTMLInputElement | null>) => {
    if (!ref) return;
    const el = ref.current;
    if (!el) return;
    // @ts-ignore
    if (typeof el.showPicker === 'function') {
      // @ts-ignore
      el.showPicker();
    } else {
      el.focus();
      el.click();
    }
  };

  return (
    <div className={styles.container}>
      <div className={styles.header}>
        <h2 className={styles.title}>Project Details</h2>
        <p className={styles.description}>Define project scope, timeline, and requirements</p>
      </div>
      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={`${styles.label} ${styles.labelGray}`}>
            ERTM Project ID
          </label>
          <input type="text" className={styles.input}  disabled />
          <p className={`${styles.additionalInfo} ${styles.additionalInfoGray}`}>
            Auto Generated by ServiceNow
          </p>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>SAP Project ID</label>
          <select
            className={styles.select}
            value={formData.sapProjectId}
            onChange={(e) => handleChange('sapProjectId', e.target.value)}
          >
            <option value="" hidden></option>
            {data?.result?.sap_project_ids?.map((id: string) => (
              <option key={id} value={id}>{id}</option>
            ))}
          </select>
          <p className={styles.additionalInfo}>If unavailable, you may proceed and update later.</p>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>
            Project Code Name <span className={styles.required}>*</span>
          </label>
          <select
            className={styles.select}
            value={formData.projectCodeName}
            onChange={(e) => handleChange('projectCodeName', e.target.value)}
          >
            <option value="" hidden></option>
            {data?.result?.project_code_names?.map((id: string) => (
              <option key={id} value={id}>{id}</option>
            ))}
          </select>
          <p className={styles.additionalInfo}>Select a name from the list, or add a new one.</p>
        </div>
      </div>

      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={styles.label}>Project Type</label>
          <select
            className={styles.select}
            value={formData.projectType}
            onChange={(e) => handleChange('projectType', e.target.value)}
          >
            <option value="" hidden></option>
            <option value="Development">Development</option>
            <option value="Proof of concept">Proof of concept</option>
            <option value="Platform build">Platform build</option>
          </select>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>Estimated Start Date</label>

          <input
            ref={startDateRef}
            type="date"
            value={formattedStart ? formData.estimatedStartDate : ''}
            onChange={(e) => handleChange('estimatedStartDate', e.target.value)}
            style={{
              position: 'absolute',
              width: '1px',
              height: '1px',
              padding: 0,
              margin: '-1px',
              overflow: 'hidden',
              clip: 'rect(0 0 0 0)',
              whiteSpace: 'nowrap',
              border: 0,
            }}
            aria-hidden={false}
          />

          <div className={styles.dateInput} onClick={() => openPicker(startDateRef)} role="button" tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                openPicker(startDateRef);
              }
            }}>
            <DateIcon />
            <input
              type="text"
              readOnly
              value={formattedStart}
              placeholder=""
              className={styles.input}
              style={{ border: 'none', padding: 0, margin: 0, background: 'transparent', color: '#282926', cursor: 'pointer' }}
              aria-label="Estimated start date"
            />
          </div>
        </div>

        <div className={styles.formGroup}>
          <label className={styles.label}>Estimated End Date</label>

          <input
            ref={endDateRef}
            type="date"
            value={formattedEnd ? formData.estimatedEndDate : ''}
            onChange={(e) => handleChange('estimatedEndDate', e.target.value)}
            style={{
              position: 'absolute',
              width: '1px',
              height: '1px',
              padding: 0,
              margin: '-1px',
              overflow: 'hidden',
              clip: 'rect(0 0 0 0)',
              whiteSpace: 'nowrap',
              border: 0,
            }}
            aria-hidden={false}
          />

          <div className={styles.dateInput} onClick={() => openPicker(endDateRef)} role="button" tabIndex={0}
            onKeyDown={(e) => {
              if (e.key === 'Enter' || e.key === ' ') {
                e.preventDefault();
                openPicker(endDateRef);
              }
            }}>
            <DateIcon />
            <input
              type="text"
              readOnly
              value={formattedEnd}
              placeholder=""
              className={styles.input}
              style={{ border: 'none', padding: 0, margin: 0, background: 'transparent', color: '#282926', cursor: 'pointer' }}
              aria-label="Estimated end date"
            />
          </div>
        </div>
      </div>

      <div className={styles.formRow}>
        <div className={styles.formGroup}>
          <label className={styles.label}>Personal or Protected Data Involved?</label>
          <select
            className={styles.select}
            value={formData.personalOrprotectedData}
            onChange={(e) => handleChange('personalOrprotectedData', e.target.value)}
          >
            <option value="" hidden></option>
            <option value="yes">Yes</option>
            <option value="no">No</option>
          </select>
        </div>
      </div>

      <div className={styles.formGroup}>
        <label className={styles.label}>Project Description</label>
        <div className={styles.textareaWrapper}>
          <textarea
            className={styles.textarea}
            value={formData.description}
            onChange={(e) => {
              setCharCount(e.target.value.length);
              handleChange('description', e.target.value);
            }}
            maxLength={80}
          />
          <div className={styles.wordCounter}>{charCount}/80</div>
        </div>
      </div>
    </div>
  );
};